name: Scheduled Script Run

on:
  push:
  schedule:
    - cron: '31 */3 * * *'  # Run at 31 minutes past every 3 hours
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    
    - name: Install dependencies
      run: uv sync
    
    - name: Install Playwright browsers
      run: uv run playwright install --with-deps chromium
    
    - name: Run script
      run: uv run python main.py
      env:
        BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
        X_BEARER_TOKEN: ${{ secrets.X_BEARER_TOKEN }}
        X_API_KEY: ${{ secrets.X_API_KEY }}
        X_API_KEY_SECRET: ${{ secrets.X_API_KEY_SECRET }}
        X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
        X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
        X_BEARER_TOKEN_2: ${{ secrets.X_BEARER_TOKEN_2 }}
        X_API_KEY_2: ${{ secrets.X_API_KEY_2 }}
        X_API_KEY_SECRET_2: ${{ secrets.X_API_KEY_SECRET_2 }}
        X_ACCESS_TOKEN_2: ${{ secrets.X_ACCESS_TOKEN_2 }}
        X_ACCESS_TOKEN_SECRET_2: ${{ secrets.X_ACCESS_TOKEN_SECRET_2 }}
    
    - name: Commit updated CSV
      if: always()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git config --local --unset-all http.https://github.com/.extraheader
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/davidpomerenke/unreported.git
        git add posted.json
        git diff --staged --quiet || git commit -m "update posted reports json [skip ci]"
        git push
